### ISSUE TITLE
Refreshed extractor says it is run out. 

### ISSUE THREAD

**Issue by Darius-Hutchison** [DavidEdwards/EVE-PI#15]
I refreshed a complex organism extractor that was on a 2 day 1 hour 30 minute cycle approximately halfway through completion,  however the App says that it has run out.

**Comment by DavidEdwards** [comment]
Does it show as run out when you look at it on the planet?

**Comment by Darius-Hutchison** [comment]
No it does not. It is also on a different planet then the other issue.

**Comment by DavidEdwards** [comment]
What timezone are you in? I thought that I fixed those issues, but perhaps something has persisted.

**Comment by DavidEdwards** [comment]
I cannot replicate this bug. Switching timezones on my phone yields the same expiration times.

As with the other bug, I will close this for now. If you come back with more information I can look at it further.
