### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by Wigster30** [DavidEdwards/EVE-PI#20]
When using the scan feature. Once I've searched and found the system I want and the app returns all the P0 through to P4s that can be made, I'm unable to scroll down the page to see results that are off the page. Horizontal Scrolling works but not vertical.

**Comment by Wigster30** [comment]
This was on a Huawei m3 8" tablet running Android 6.0

**Comment by DavidEdwards** [comment]
Fixed!
