### ISSUE TITLE
Feature: Stored favorites to scan section

### ISSUE THREAD

**Issue by JeffreyTeague** [DavidEdwards/EVE-PI#21]
Add stored favorite to scan section, so we do not to search each time for repeat systems.

**Comment by DavidEdwards** [comment]
Sounds good - do you find the scan feature useful? I'm not sure it is giving enough information to make it useful at the moment.

**Comment by JeffreyTeague** [comment]
I can tell direction. This will be very useful.

**Comment by DavidEdwards** [comment]
I ended up adding a favourites button. It doesn't cache the data, but it will at least allow users to not need to search each time.
