### ISSUE TITLE
Old Extractors still showing

### ISSUE THREAD

**Issue by twillert** [DavidEdwards/EVE-PI#23]
Hi,
I have a char who had 2 extractors at one point in time. I changed these 2 planets to a factory-only setup without any extractors. The app is still showing these old extractors as expired (and flashy red).
After a few days I changed these 2 planet back to a setup including extractors. The original old extractors are still shown as expired. The new extractors are showing correctly.

If there is no way to detect if an extractor has been removed or not, then I would suggest to add an a feature to manually remove old extractors.

Let me know if you need additional info for this issue?

**Comment by DavidEdwards** [comment]
That was supposed to be fixed in the last version (uploaded yesterday). If that is still there, then my change didn't fix it.

I'll look at it again!

I want to avoid giving a manual method of removing, because it should really be entirely automated.

**Comment by twillert** [comment]
After updating the app just the old extractors went away. Bug fixed, it seems.

**Comment by DavidEdwards** [comment]
Good news, thanks for the update!
