### ISSUE TITLE
Add triggers for colony structures

### ISSUE THREAD

**Issue by DavidEdwards** [DavidEdwards/EVE-PI#3]
User should be able to add triggers to their structures.

Example
- If launchpad 70% full -> create alert

**Comment by DavidEdwards** [comment]
Work on this after first release.

**Comment by frayel** [comment]
Firstly congratulations for the app.This is what i was waiting for years. It is very nice and i don't found a bug yet. Hehe.

A nice trigger could look for the routes. For example to alert when is a missing route that you forgot.

Other interesting alert could be used to optimize factroies. For example: a extractor producing 1000 and other 8000 routing to a factory that requires 6000 from each. Will be a shortage of first material and a excess of the other. The trigger could alert this shortages and when a storage is acumulating.

**Comment by DavidEdwards** [comment]
It seems that this may not be possible at the moment. The current ESI API does not support detecting storage quantities. Hopefully this will be added to the API in the future. Until then, I will keep this on the backburner.

**Comment by DavidEdwards** [comment]
Thanks to the work of tsuthers-ccpgames (and presumably others). Work has now begun on implementing changes that will bring storage and factories all together.

**Comment by DavidEdwards** [comment]
Condensing this issue into #40
