### ISSUE TITLE
Navigation Drawer character list.

### ISSUE THREAD

**Issue by captainstu72** [DavidEdwards/EVE-PI#34]
The navigation drawer gets covered by the status bar. This makes the top character harder to select. The character list also does not have the same margins and line height as the other menu items. This makes selecting them more challenging.

**Comment by DavidEdwards** [comment]
Good points! May I ask how many characters you have set up? I set it so that the height is reduced when you have more characters, to ensure that it doesn't take up the entire side bar.

That said, I have thought about extracting the character list into a dialog of some kind.

**Comment by captainstu72** [comment]
7 characters currently. Have you considered the spinner type of account list used on the GMail app?

**Comment by DavidEdwards** [comment]
Not a bad idea. I'll look at implementing something similar. That will save a lot of space.

**Comment by DavidEdwards** [comment]
Massive changes made here. New character list implemented. Sorted firstly by who has expired extractors and then alphabetically.

Should be much easier to refresh those extractors now.
