### ISSUE TITLE
Feature request: indicate unrouted extractors on extractor view

### ISSUE THREAD

**Issue by HTL2001** [DavidEdwards/EVE-PI#36]
The "errors" entry tends to display a bunch of "bad routes" (which don't really do anything, it seems) and can bury the display of unrouted extractors.  The error condition also is serious enough that it shouldn't be flaggable as "done"

**Comment by DavidEdwards** [comment]
The next version will not duplicate the same error in the list over and over again whenever it is discovered. Instead, errors will only show once in the list.

It was previously just a log, one after the other.
