### ISSUE TITLE
Factory Efficiency

### ISSUE THREAD

**Issue by SasugaTV** [DavidEdwards/EVE-PI#49]
It would be nice to know if my factories are running constantly, or if there are gaps where they are waiting for resources. And thus are only running 70% or something, for the given planet, and for the given factory.

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time.

This is something I was working on a while ago. I was working on a simulation system. It is not a priority for me at the moment, as I have not played EVE in a while. Perhaps sometime in the future.
