### ISSUE TITLE
Planet moving

### ISSUE THREAD

**Issue by DjSni** [DavidEdwards/EVE-PI#50]
I noticed that when you disable the PI on one planet and rebuild it on another planet, which is still listed on the extractor tab.
In my opinion, the app should automatically remove the planet when it is no longer in use.
I had to take the detour and clear the entire cache.

**Comment by DavidEdwards** [comment]
Yes, that is the current fix for this issue. Clearing the cache. There is an option in the app settings (not necessary to delete the Android App cache).
