### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by DjSni** [DavidEdwards/EVE-PI#51]
a way to set the timers (when I am reminded) in the app would make sense.

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time.

The way it works currently, is that it uses Google services to ensure that your device runs these checks with jobs from other apps. To reduce the workload of your phone (and save battery).

You can set the interval with which it checks if you like. I won't be adding any specific times to check the API though.
