### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by Strixen** [DavidEdwards/EVE-PI#52]
Can you add a function to consolidate the notifications? Whenever i finish an extraction the app gives me 5-7 notifications on top of each other not sure if it's a bug or not, but could you add a new notification lockout timer or something. So instead of getting 7 notifications at the same time I get one that is instead updated 6 times.

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time.

The way the system works is that every extractor runs its own notification. This is standard operation in Android. It allows me to group the notifications into one swipe-able group. It also allows the user to investigate each one individually.
