### ISSUE TITLE
Old planets still appear in my app

### ISSUE THREAD

**Issue by emarinuk** [DavidEdwards/EVE-PI#53]
That's it :) I can still see the 6 planeta y abandoned and decommissioned a while ago. Got screenshots if you need them. Thanks.

**Comment by emarinuk** [comment]
![screenshot_2018-09-05-00-30-19-667_dae evepi](https://user-images.githubusercontent.com/34950910/45062924-1f888a80-b0a3-11e8-95f0-ab6adad5caa3.png)
![screenshot_2018-09-05-00-30-16-616_dae evepi](https://user-images.githubusercontent.com/34950910/45062925-20212100-b0a3-11e8-8ce7-cd9cdb6c00ee.png)

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time.

Try clearing the cache - in the App settings, go to cache control.
