### ISSUE TITLE
Extracters

### ISSUE THREAD

**Issue by Omega2019** [DavidEdwards/EVE-PI#55]
Extracter list will not up date. Is there a delay for them to update or for new ones to be seen?

**Comment by DavidEdwards** [comment]
Try clearing the cache - in the App settings, go to cache control.

That should fix it for you.

**Comment by Omega2019** [comment]
Ok it some what fix itself but it's still has to many factors for just 2 planets it's like it has double vision when it comes to them.
Sent from Yahoo Mail on Android 
 
  On Tue, Nov 13, 2018 at 1:34 PM, David Edwards<notifications@github.com> wrote:   
Try clearing the cache - in the App settings, go to cache control.

That should fix it for you.

**Comment by DavidEdwards** [comment]
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time. If you are still having this issue, post a new issue. Posting a screenshot of what you see would be really useful.

**Comment by Omega2019** [comment]
I'll do what I can.
Sent from Yahoo Mail on Android 
 
  On Wed, Jan 23, 2019 at 9:59 AM, David Edwards<notifications@github.com> wrote:   
Just clearing up some old issues. Sorry for not paying attention here, I haven't been playing EVE for some time. If you are still having this issue, post a new issue. Posting a screenshot of what you see would be really useful.
