### ISSUE TITLE
Decommissioned planets still shown

### ISSUE THREAD

**Issue by SpawnageLoong** [DavidEdwards/EVE-PI#57]
Initially, I had all of my PI set up in a high-sec system, but I've since moved them all into Null-Sec and thus decommissioned the command centers in the old system but all the infrastructure for those planets still show up in the app. I've thought of putting a command center back on those planets and manually decommissioning each extractor and factory, but I've already used all the available planets I have and I'd rather not decommission a command centre and lose all the buildings on it in case my idea doesn't work.

**Comment by DavidEdwards** [comment]
See if this works...

Go to the settings for the app, then cache control. See if deleting that cache fixes it for you.

**Comment by SpawnageLoong** [comment]
That worked! Thanks!
