### ISSUE TITLE
No idea? App wants me to post this.

### ISSUE THREAD

**Issue by GojuSuzi** [DavidEdwards/EVE-PI#59]
Opened app, it started logging in, then redirects to this page. 

Still can't find any extractors or whatnot, but that's a known thing, but the app apparently is now by default asking used to submit bug reports on launch so dunno if that's intentional or a new glitch

**Comment by DavidEdwards** [comment]
That certainly is strange. The system shouldn't redirect you automatically here. Crashes are automatically sent to a tracker. Github is for manually reporting issues or asking for features. 

In fact, looking at the code, the only time it will ever happen is when you manually press the button in the menu.

If it is logging in, you should definitely see your extractors. The only time that could not be the case, is if you are not a paying EVE customer. In which case you might get "weirdness" from the Planetary APIs.
