### ISSUE TITLE
Feature Request: Units not m3

### ISSUE THREAD

**Issue by Velkyn-Elamshin** [DavidEdwards/EVE-PI#60]
Just wondering if it could be added in the option to display stored materials in either cubic meters (m3) or in actual units? This app is really handy, love using it, and can see more players finding it even more useful if it displayed each materials in units. 

Thanks, keep up the great work!  ;)

-Vel

**Comment by DavidEdwards** [comment]
That should be simple.

I could add it as an option in the App settings.

**Comment by DavidEdwards** [comment]
This will be in the next version.
