### ISSUE TITLE
EVE Planetary Interaction

### ISSUE THREAD

**Issue by vulcherdawg** [DavidEdwards/EVE-PI#61]
Id like to see this Planetary Interaction app have features like seeing QTY of resources from EVE and accurate wallet balances. Maybe trading hub market prices. And a schematics with required resources list for production.

**Comment by DavidEdwards** [comment]
Sorry for the extremely late reply. I am going through the old issues on this repository.

That would be a lot of extra work, outside of the PI scope.

I never wanted this App to delve too deep into the business of the player.
