### ISSUE TITLE
Wrong number of factories

### ISSUE THREAD

**Issue by Xo6oToK** [DavidEdwards/EVE-PI#66]
Double factories on screen. I have 6 at each planet, but see 12.

**Comment by DavidEdwards** [comment]
Duplicate of #54. This particular system is not production ready.

**Comment by Xo6oToK** [comment]
Ok, I'm sorry. I'm noob and say first what i see. I don't check previous
reports. My bad.

пн, 13 янв. 2020 г., 15:21 David Edwards <notifications@github.com>:
