### ISSUE TITLE
Show contents

### ISSUE THREAD

**Issue by frayel** [DavidEdwards/EVE-PI#7]
Should be possible to see the content from all the storages of each planet (launchpads and storages) and the total value based on jita prices.

**Comment by frayel** [comment]
Also. Could be possible to see how much each structure is producing per hour.

For example:
Extractor x: 3000 base metals / hour (15000 isk/h)
Factory y: 30 transmitters* / hour ( 35000 isk/hour)

*The factory production not allways will be the max cycle. Could be possible to subtract the shortages. (How many hours the factory stayed stopped based on the extractor production)

**Comment by DavidEdwards** [comment]
It seems that this may not be possible at the moment. The current ESI API does not support detecting storage quantities. Hopefully this will be added to the API in the future. Until then, I will keep this on the backburner.

**Comment by frayel** [comment]
Looking forward for new updates on the ESI API. :)
Thanks

**Comment by DavidEdwards** [comment]
Looks like there is some movement on this in the ESI. Hopefully. 

https://github.com/ccpgames/esi-issues/issues/161

I'll start writing the framework for this soon.

**Comment by DavidEdwards** [comment]
Thanks to the work of tsuthers-ccpgames (and presumably others). Work has now begun on implementing changes that will bring storage and factories all together.

**Comment by DavidEdwards** [comment]
Condensing this issue into #40
