### ISSUE TITLE
Suggestion: link to Google Calendar

### ISSUE THREAD

**Issue by Zupertails** [DavidEdwards/EVE-PI#71]
Simple request, but possibly tricky to implement : link the timers to e.g. Google Calendar.
I'll also explain why.
Eve PI doesn't always run in the background, on phones with limited RAM. This would solve that issue.

Grtz and o7

**Comment by DavidEdwards** [comment]
The App doesn't run permanently in the background. It has events to run regularly at correct intervals.

If it isn't working for you, that may be another problem.

https://dontkillmyapp.com/
