### ISSUE TITLE
App don't display PI's assets

### ISSUE THREAD

**Issue by stuffnex** [DavidEdwards/EVE-PI#72]
First, thanks for this app, it's great, tho having registered my character I have just random and not real warning on my extractor units, do not display any storage... It's like it's getting half of the data it requires to display something of sense.
It would be awesome have this working.

**Comment by DavidEdwards** [comment]
Sorry for the extremely late reply. I am going through the old issues on this repository.

I don't really understand. If this is still an issue, feel free to make another issue.
