### ISSUE TITLE
Eve pi app, not removing deleted planets

### ISSUE THREAD

**Issue by sibaz** [DavidEdwards/EVE-PI#77]
Hi, so in short had pi on several planets in high sec, but moved to null sec, so deleted the ccu's on all/most of the hs planets before installing new in null.  
Now eve pi shows me alerts for all the planets i'm no-longer using, in addition to the planets i am now using.

So either eve is reporting on too much, or eve pi is caching things no-longer relevant.

This should be easy to reproduce, so ill try to create pi on a planet then kill it and see if it continues to report.

**Comment by DavidEdwards** [comment]
This is almost certainly to do with how the app caches planets.

Go to the app settings and find cache control. You can delete the data and pull it again. That will fix the reporting, hopefully.
