### ISSUE TITLE
Storage - Space Port is Not Showing Accurate Storage.

### ISSUE THREAD

**Issue by freelanceontime** [DavidEdwards/EVE-PI#83]
![Screenshot_20210606-205840_Eve PI](https://user-images.githubusercontent.com/6866670/120938337-13c1cb00-c70a-11eb-966a-6315a7e708ac.jpg)
It has been observed that when filling up the space port with pure materials the storage page fails to show any updated figures if used by the factories that are connected to it. It is expected that as the factories use the materials within the storage the figures update. This would benofit the user in knowing when to refil the spaceports when nessesary.

Steps to reproduce.
1. Create port
2. Add resources 
3. Add factories and nessesary routes
4. Observe after 2 hours
5. Space port shows still full of resources 
6. Check in game and observe resources are used

**Comment by DavidEdwards** [comment]
Thank you for the full steps to reproduce etc. Unfortunately this is a completely normal operation of the App. The system will not work until you visit your planets again (in game).

The reason for this, is that the data is only updated on the side of CCP, when you access it in-game.
